Fix/sql
lolothi/ProjetFlask pull request #11
Opened 2023-03-27 14:59 UTC by FAUCHERYBenoit

2023-03-28 21:13 UTC, lolothi requested changes

2023-03-28 21:13 UTC, lolothi commented on app.py
> +PATH = "/home/vincent/myproject/ProjetFlask/"
lien pas vraiment utilisable sur d'autre mchine que la tienne

2023-03-28 21:13 UTC, lolothi commented on confSQL.sql
> +
tu peux ajouter un username stp ?

2023-03-29 12:36 UTC, Vin100fun commented on app.py
> +PATH = "/home/vincent/myproject/ProjetFlask/"
Edit : J'ai supprimé mon PATH, j'ai gardé le répertoire parent comme PATH pour la database

2023-03-29 12:37 UTC, Vin100fun commented on confSQL.sql
> +
Je le ferai dans un prochain push, mais on avait parlé d'utiliser le mail comme login. 
A voir ensemble donc

2023-03-29 13:25 UTC, FAUCHERYBenoit commented on confSQL.sql
> +
Pour moi le username remplace nom + prénom, ça permet de pas avoir à faire de manip inutiles dans le code avec le nom et prénom

2023-03-29 15:43 UTC, lolothi approved these changes

2023-03-29 15:43 UTC, merged